//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExampleSideServerProcessing.Models
{
    using System;
    using System.Collections.Generic;

    public partial class FIFA
    {
        public int ID { get; set; }

        private string nombre { get; set; }
        public string Nombre
        {
            get { return (nombre == null) ? "" : nombre; }
            set { nombre = value; }
        }

        private string nombreCompleto;
        public string NombreCompleto
        {
            get { return (nombreCompleto == null) ? "" : nombreCompleto; }

            set { nombreCompleto = value; }
        }

        private string club;
        public string Club
        {
            get { return (club == null) ? "" : club; }
            set { club = value; }
        }

        private string liga;
        public string Liga
        {
            get { return (liga == null) ? "" : liga; }
            set { liga = value; }
        }


        private DateTime fechaNacimiento;
        public System.DateTime FechaNacimiento
        {
            get { return (fechaNacimiento == null) ? DateTime.MinValue : fechaNacimiento; }
            set { fechaNacimiento = value; }
        }

        public int AlturaCM { get; set; }
        public int PesoKG { get; set; }

        private string nacionalidad;
        public string Nacionalidad
        {
            get { return (nacionalidad == null) ? "" : nacionalidad; }
            set { nacionalidad = value; }
        }
        public double ValorEuropa { get; set; }

        private string piePreferido;
        public string PiePreferido
        {
            get { return (piePreferido == null) ? "" : piePreferido; }
            set { piePreferido = value; }
        }

        private string pieEsp;
        public string PieEsp 
        {
            get { return (pieEsp == null) ? "" : pieEsp; }
            set { pieEsp = value; }
        }
    }
}
