//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExampleSideServerProcessing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIFA
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string NombreCompleto { get; set; }
        public string Club { get; set; }
        public string Liga { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public int AlturaCM { get; set; }
        public int PesoKG { get; set; }
        public string Nacionalidad { get; set; }
        public double ValorEuropa { get; set; }
        public string PiePreferido { get; set; }
        public string PieEsp { get; set; }
    }
}
